version: "3.8"

services:
    mysqldb:
        image: mysql:5.7
        container_name: fc-mysql
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_TCP_PORT=${MYSQL_DOCKER_PORT}
        ports:
            - ${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}

        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 5s
            retries: 10
           
